export const sequencingData = [
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Whole Genome Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "200 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Whole Genome Sequencing (PCR-free)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Whole Exome Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "100 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Complete Plasmid DNA Sequencing",
				sampleType: "Plasmid DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Human/Mouse Mitochondrial DNA (mtDNA) Sequencing-multiplex PCR",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 200 ng",
				minimumQuantity: "50 ng",
				minimumConcentration: "5 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Human/Mouse Mitochondrial DNA (mtDNA) Sequencing-probes",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "200 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Chloroplast DNA (cpDNA) Sequencing",
				sampleType: "Plants tissue (Green tissue)",
				recommendedQuantity: "≥ 5 g",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Viral Genome Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Amplicon Sequencing",
				sampleType: "Purified Amplicon",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "GBS/ddRAD",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 300 ng",
				minimumQuantity: "100 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "BSA (Bulk Segregant Analysis)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 2 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "2b-RAD",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 200 ng",
				minimumQuantity: "50 ng",
				minimumConcentration: "5 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Metagenome Sequencing",
				sampleType: "Metagenome DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "20 ng",
				minimumConcentration: "5 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "16S/18S/ITS Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 100 ng",
				minimumQuantity: "10 ng",
				minimumConcentration: "1 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "SNP Microarray",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 300 ng",
				minimumQuantity: "100 ng",
				minimumConcentration: "8 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "DNA Methylation Microarray",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "8 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "SSR Genotyping",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "200 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "HLA Typing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 200 ng",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "HLA Typing",
				sampleType: "Cell, PMBC",
				recommendedQuantity: "≥ 1×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "HLA Typing",
				sampleType: "Blood",
				recommendedQuantity: "≥ 1 mL",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "HLA Typing",
				sampleType: "Buccal Swab",
				recommendedQuantity: "2",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "HLA Typing",
				sampleType: "Dried blood spot (DBS)",
				recommendedQuantity: "2 completely filled spots, each 10 mm in diameter",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "TCR-Seq",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 2 µg",
				minimumQuantity: "20 ng/µL",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "TCR-Seq",
				sampleType: "PMBC",
				recommendedQuantity: "≥ 2 x105",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "TCR-Seq",
				sampleType: "Animal tissue",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "TCR-Seq",
				sampleType: "Blood",
				recommendedQuantity: "≥ 0.5 mL",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Whole Genome Sequencing (PacBio)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 3 µg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "80 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Whole Genome Sequencing (Nanopore)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 5 µg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Plasmid Sequencing (Nanopore)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "500 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500ng",
				minimumQuantity: "Not applicable",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Tissue",
				recommendedQuantity: "1-3g",
				minimumQuantity: "1 g",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Thallus",
				recommendedQuantity: "5 g",
				minimumQuantity: "3 g",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Interstitial Fluid",
				recommendedQuantity: "3-5 mL",
				minimumQuantity: "1 mL",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Environmental Samples",
				recommendedQuantity: "3-5g",
				minimumQuantity: "1 g",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Full-Length 16S/18S/ITS Amplicon",
				sampleType: "Water filter membrane",
				recommendedQuantity: "3",
				minimumQuantity: "1",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Long-Read Metagenomic Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 2 ug",
				minimumQuantity: "Not applicable",
				minimumConcentration: "30ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Long-Read Metagenomic Sequencing",
				sampleType: "Tissue",
				recommendedQuantity: "2 g",
				minimumQuantity: "1 g",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Long-Read Metagenomic Sequencing",
				sampleType: "Interstitial Fluid",
				recommendedQuantity: "6-10 mL, sediment 2g",
				minimumQuantity: "2 mL, sediment",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Long-Read Metagenomic Sequencing",
				sampleType: "Environmental Samples",
				recommendedQuantity: "6g",
				minimumQuantity: "2 g",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Long Read",
				application: "Long-Read Metagenomic Sequencing",
				sampleType: "Water filter membrane",
				recommendedQuantity: "6",
				minimumQuantity: "2",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "MeDIP-Seq/hMeDIP-seq",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 2 µg",
				minimumQuantity: "1 µg",
				minimumConcentration: "20 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "WGBS (Whole Genome Bisulfite Sequencing)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 μg",
				minimumQuantity: "200 ng",
				minimumConcentration: "10 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "WGBS (Whole Genome Bisulfite Sequencing)",
				sampleType: "Cell",
				recommendedQuantity: "≥ 1 x106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "WGBS (Whole Genome Bisulfite Sequencing)",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 50 mg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "RRBS (Reduced representation bisulfite sequencing)",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 1 µg",
				minimumQuantity: "20 ng",
				minimumConcentration: "20 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "RRBS (Reduced representation bisulfite sequencing)",
				sampleType: "Cell",
				recommendedQuantity: "≥ 5 x106",
				minimumQuantity: "3×103",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "RRBS (Reduced representation bisulfite sequencing)",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 30 mg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Targeted Bisulfite Sequencing",
				sampleType: "Genomic DNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "50 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Targeted Bisulfite Sequencing",
				sampleType: "Cell",
				recommendedQuantity: "≥ 1×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "Targeted Bisulfite Sequencing",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 20 mg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "ChIP-seq",
				sampleType: "ChIPed DNA",
				recommendedQuantity: "≥ 10 ng",
				minimumQuantity: "5 ng",
				minimumConcentration: "1 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "ChIP-seq",
				sampleType: "Cell",
				recommendedQuantity: "≥ 2 x107",
				minimumQuantity: "1 x105",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "ChIP-seq",
				sampleType: "Tissue",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "DAP-seq",
				sampleType: "TF",
				recommendedQuantity: "≥ 5 µg",
				minimumQuantity: "1 µg",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "DAP-seq",
				sampleType: "Cell",
				recommendedQuantity: "≥ 5 x106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "DAP-seq",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "200 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "ATAC-seq",
				sampleType: "Cell",
				recommendedQuantity: "≥ 1×106",
				minimumQuantity: "5×104",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "ATAC-seq",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "200mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "CUT&Tag",
				sampleType: "Cell",
				recommendedQuantity: "≥ 1×105",
				minimumQuantity: "5×104",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "DNA Sequencing",
				category: "Short Read - Illumina",
				application: "CUT&Tag",
				sampleType: "Tissue",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "200mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Whole Transcriptome Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 3 μg",
				minimumQuantity: "1 μg",
				minimumConcentration: "20 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "UMI RNA-seq",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 2 μg",
				minimumQuantity: "1 μg",
				minimumConcentration: "50 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Low input RNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 20 ng",
				minimumQuantity: "20 pg",
				minimumConcentration: "1 pg/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "mRNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 500 ng",
				minimumQuantity: "200 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "mRNA Sequencing",
				sampleType: "Cells",
				recommendedQuantity: "≥ 1×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "mRNA Sequencing",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 50 mg",
				minimumQuantity: "10 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Total RNA/LncRNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 2 μg",
				minimumQuantity: "500 ng",
				minimumConcentration: "50 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Total RNA/LncRNA Sequencing",
				sampleType: "Cells",
				recommendedQuantity: "≥ 2×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Total RNA/LncRNA Sequencing",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "100 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Small Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 1 μg",
				minimumQuantity: "200 ng",
				minimumConcentration: "20 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Small Sequencing",
				sampleType: "Cells",
				recommendedQuantity: "≥ 2×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Small Sequencing",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "100 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CircRNA Sequencing (linear RNA digestion)",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 5 μg",
				minimumQuantity: "2 μg",
				minimumConcentration: "50 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CircRNA Sequencing (linear RNA digestion)",
				sampleType: "Cells",
				recommendedQuantity: "≥ 2×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CircRNA Sequencing (linear RNA digestion)",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "100 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Metatranscriptome",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 4 μg",
				minimumQuantity: "3 μg",
				minimumConcentration: "50 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Metatranscriptome",
				sampleType: "Cells",
				recommendedQuantity: "≥ 5×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Metatranscriptome",
				sampleType: "Environmental Samples",
				recommendedQuantity: "≥ 1.5g",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Bacterial RNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 1 μg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Bacterial RNA Sequencing",
				sampleType: "Cells",
				recommendedQuantity: "≥ 1x107",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Degradome sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 20 μg",
				minimumQuantity: "15 μg",
				minimumConcentration: "100 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "TCR-seq",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 100 ng",
				minimumQuantity: "Not applicable",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CAGE-seq",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 5 μg",
				minimumQuantity: "3 μg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CAGE-seq",
				sampleType: "Cells",
				recommendedQuantity: "≥ 2×107",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "CAGE-seq",
				sampleType: "Tissue",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "200 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Ribo-seq",
				sampleType: "Cells",
				recommendedQuantity: "≥ 5×106-107",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Ribo-seq",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 400 mg",
				minimumQuantity: "200 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Dual RNA-seq",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 1 μg",
				minimumQuantity: "200 ng",
				minimumConcentration: "10 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Dual RNA-seq",
				sampleType: "Cells",
				recommendedQuantity: "≥ 5×106",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Dual RNA-seq",
				sampleType: "Tissue (Human/Animal/Plant)",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "100 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "Exosomal RNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 100 ng",
				minimumQuantity: "Not applicable",
				minimumConcentration: "20 ng/μL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Long Read",
				application: "Iso-Seq",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 2 μg",
				minimumQuantity: "600 ng",
				minimumConcentration: "30 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Long Read",
				application: "Nanopore Full-Length Transcripts",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 2 μg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Long Read",
				application: "Nanopore Direct RNA Sequencing",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 15 μg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "MeRIP (Methylated RNA Immunoprecipitation)",
				sampleType: "Total RNA",
				recommendedQuantity: "≥ 10 μg",
				minimumQuantity: "2 μg",
				minimumConcentration: "1 ng/µL",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "MeRIP (Methylated RNA Immunoprecipitation)",
				sampleType: "Cell",
				recommendedQuantity: "≥ 1×107",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "RNA Sequencing",
				category: "Short Read - Illumina",
				application: "MeRIP (Methylated RNA Immunoprecipitation)",
				sampleType: "Tissue",
				recommendedQuantity: "≥ 500 mg",
				minimumQuantity: "200 mg",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "ScRNA-seq",
				sampleType: "Single cell suspension, Fresh tissue",
				recommendedQuantity: "2×106 cells",
				minimumQuantity: "1×106 cells",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "SnRNA-seq",
				sampleType: "Snap frozen tissue",
				recommendedQuantity: "≥ 100mg(Please contact us for details)",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "10X Visium Spatial Transcriptome",
				sampleType: "OCT embedded tissue, FFPE",
				recommendedQuantity: "6.5mm×6.5mm",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "Single Cell Genome Sequencing",
				sampleType: "Whole blood anticoagulated with EDTA",
				recommendedQuantity: "≥ 5mL",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "Single Cell Genome Sequencing",
				sampleType: "Cells",
				recommendedQuantity: "1-103, Single cells are stored in 1xPBS buffer (without Ca2+, Mg2+), the volume is within 2 μL",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "Single Cell Genome Sequencing",
				sampleType: "DNA",
				recommendedQuantity: "≥ 0.5pg",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "ScWGBS",
				sampleType: "Cell lines, primary cells, fresh tissue, frozen cells",
				recommendedQuantity: "Use 200µl PCR tubes to store cells (single or multiple cells), 5µl of lysate per tube, and no more than 1µl of buffer when collecting cells",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Single Cell Sequencing/Spatiotemporal Genomics",
				category: "Short Read - Illumina",
				application: "ScRRBS",
				sampleType: "Cell lines, primary cells, fresh tissue, frozen cells",
				recommendedQuantity: "Use 200µl PCR tubes to store cells (single or multiple cells), 5µl of lysate per tube, and no more than 1µl of buffer when collecting cells. ≥3 biological replicates",
				minimumQuantity: "Not applicable",
				minimumConcentration: "Not applicable",
				platform: "Not applicable",
				dataAmount: "Not applicable",
				volumeRequirement: "Not applicable"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "NA",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Novaseq-PE150",
				dataAmount: "X<30G",
				volumeRequirement: "≥15 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Novaseq-PE150",
				dataAmount: "30G≤X＜100G",
				volumeRequirement: "≥25 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Novaseq-PE150",
				dataAmount: "100G≤X≤400G",
				volumeRequirement: "≥50 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Novaseq-PE150",
				dataAmount: "400G＜X＜800G",
				volumeRequirement: "≥70 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Novaseq-PE150",
				dataAmount: "800G",
				volumeRequirement: "≥100 μL (additional 70μL for one more lane)"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Nova- PE250",
				dataAmount: "X<30GM",
				volumeRequirement: "≥15 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Nova- PE250",
				dataAmount: "30M≤X＜100M",
				volumeRequirement: "≥25 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Nova- PE250",
				dataAmount: "100M≤X<400M",
				volumeRequirement: "≥50 μL"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "2 ng/μL",
				platform: "Nova- PE250",
				dataAmount: "400M",
				volumeRequirement: "≥100 μL (additional 70μL for one more lane)"
			},
			{
				nucleicAcid: "Ready To Run Library (RTRL)",
				category: "Short Read - Illumina",
				application: "Not applicable",
				sampleType: "Not applicable",
				recommendedQuantity: "Not applicable",
				minimumQuantity: "Not applicable",
				minimumConcentration: "1 ng/μL",
				platform: "MiSeq-PE300",
				dataAmount: "1 Flowcell",
				volumeRequirement: "≥10 μL"
			}
];
